http://localhost:3000

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Arafat",
  "email": "test2@gmail.com",
  "password": "TestPWD@123"
} 

###

GET http://localhost:3000/user
`